services:
  jupyter_lab:
    restart: always
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    expose:
      - "${port}"
    networks:
      - ${network}
    environment:
      - VIRTUAL_PORT=${port}
      - VIRTUAL_HOST=${domain}
      - LETSENCRYPT_HOST=${domain}
      - LETSENCRYPT_EMAIL=${letsencrypt_email}
networks:
  ${network}:
    external: true